version: '3'

services:
  app:
    env_file:
      - ./.env 
    build:
      context: ./
      dockerfile: Dockerfile 
    ports: 
      - "8080:8080"
    environment:
      - POSTGRE_DSN=postgres://zach:supersecretpassword@postgres:5432/chat-app?sslmode=disable
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zach
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: chat-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
